### ISSUE TITLE
Problem with running zero-shot ensemble？

### ISSUE THREAD

**Issue by lijiajun520** [zhiheLu/Ensemble_VLM#2]
Prompt ensembling (n=1)
Traceback (most recent call last):
  File "/data1/mazc/LJJ/Ensemble_VLM/train.py", line 290, in <module>
    main(args)
··········
  File "/home/mazc/anaconda3/envs/envlm/lib/python3.9/site-packages/torch/nn/functional.py", line 1679, in softmax
    ret = input.softmax(dim)
RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'Half'

my question：
I encountered this issue while running ZSEN. Is it due to incorrect parameter settings or incorrect environment? I hope you can answer it, thank you!

**Comment by zhiheLu** [comment]
It seems you use softmax on a Half tensor. Please show the whole logs for better analyzing the issue. Thanks.
